# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='name_zun',
        ),
        migrations.RemoveField(
            model_name='proficiency',
            name='name_zun',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='name_zun',
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='skills',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_applyied',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_retired',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True, max_length=500, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(help_text='Укажите должность сотрудника', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.Job', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Действующий'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='job',
            name='knowledge',
            field=models.ManyToManyField(related_name='know_list', to='cmp.Knowledge', verbose_name='Знания'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='job',
            name='proficiency',
            field=models.ManyToManyField(related_name='prof_list', to='cmp.Proficiency', verbose_name='Умения'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='skills_list', to='cmp.Skills', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='proficiency',
            name='discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
