# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0006_auto_20180327_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ManyToManyField(help_text='Укажите должность сотрудника', to='cmp.Job', verbose_name='Должность'),
        ),
    ]
