# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0007_auto_20180327_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Укажите должность сотрудника', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.Job', verbose_name='Должность'),
        ),
    ]
