# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0008_auto_20180327_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='Опыт работы'),
        ),
    ]
